# Generated by Django 5.2.1 on 2025-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relaciones', '0002_character_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='Relaciones.movie'),
        ),
    ]
